/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenlab1p2_salvadormacias;

import java.util.ArrayList;

/**
 *
 * @author Apple
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        mostrarElementosEmpleado(false);
        mostrarElementosCivil(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton_empleado = new javax.swing.JToggleButton();
        boton_civil = new javax.swing.JToggleButton();
        label_nombre = new javax.swing.JLabel();
        label_apellido = new javax.swing.JLabel();
        label_departamento = new javax.swing.JLabel();
        label_nacimiento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_puesto = new javax.swing.JLabel();
        label_experiencia = new javax.swing.JLabel();
        text_departamento = new javax.swing.JTextField();
        text_apellido = new javax.swing.JTextField();
        text_nacimiento = new javax.swing.JTextField();
        text_nombre = new javax.swing.JTextField();
        text_puesto = new javax.swing.JTextField();
        text_motivoRegistro = new javax.swing.JTextField();
        label_motivoRegistro = new javax.swing.JLabel();
        text_yearsXp = new javax.swing.JTextField();
        boton_registrar = new javax.swing.JToggleButton();
        boton_morstarTodos = new javax.swing.JToggleButton();
        boton_buscarPorID = new javax.swing.JToggleButton();
        boton_estadisticas = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        text_BuscarID = new javax.swing.JTextField();
        label_buscarID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione el tipo a registrar: ");

        boton_empleado.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        boton_empleado.setText("Empleado");
        boton_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_empleadoMouseClicked(evt);
            }
        });

        boton_civil.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        boton_civil.setText("Civil");
        boton_civil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_civilMouseClicked(evt);
            }
        });

        label_nombre.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_nombre.setText("Nombre: ");

        label_apellido.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_apellido.setText("Apellido:");

        label_departamento.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_departamento.setText("Departamento(Francisco Morazan,Cortes,Comayagua)");

        label_nacimiento.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_nacimiento.setText("Año de nacimiento: ");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Seleccione el tipo a registrar: ");

        label_puesto.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_puesto.setText("Puesto: ");

        label_experiencia.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_experiencia.setText("Años de experiencia: ");

        label_motivoRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_motivoRegistro.setText("Motivo del registro: ");

        boton_registrar.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        boton_registrar.setText("Registrar");
        boton_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_registrarMouseClicked(evt);
            }
        });

        boton_morstarTodos.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        boton_morstarTodos.setText("Mostrar todos");

        boton_buscarPorID.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        boton_buscarPorID.setText("Buscar por ID");

        boton_estadisticas.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        boton_estadisticas.setText("Ver estadisticas");
        boton_estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_estadisticasMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        label_buscarID.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        label_buscarID.setText("Buscar ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(boton_empleado)
                        .addGap(102, 102, 102)
                        .addComponent(boton_civil)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_motivoRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_motivoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_experiencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_yearsXp, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_apellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_puesto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_nacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_departamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                                .addComponent(text_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boton_registrar)
                                .addGap(56, 56, 56)
                                .addComponent(boton_morstarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(boton_buscarPorID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(label_buscarID)
                                .addGap(40, 40, 40)
                                .addComponent(text_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(boton_estadisticas)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jLabel6)
                    .addContainerGap(608, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(boton_civil)
                                .addComponent(boton_empleado))
                            .addComponent(jLabel1))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nombre))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_apellido)
                            .addComponent(text_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_nacimiento)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_departamento)
                    .addComponent(text_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_experiencia)
                    .addComponent(text_yearsXp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_motivoRegistro)
                    .addComponent(text_motivoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_morstarTodos)
                            .addComponent(boton_registrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_buscarPorID)
                            .addComponent(boton_estadisticas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_BuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_buscarID))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(317, 317, 317)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 930, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_registrarMouseClicked
        jTextArea1.setText("negro");

        String nombre = text_nombre.getText();
        String apellido = text_apellido.getText();
        String nacimiento = text_nacimiento.getText();
        String dep = text_departamento.getText();
        String puesto = text_puesto.getText();
        String experiencia = text_yearsXp.getText();
        String motivo_reg = text_motivoRegistro.getText();
        lista_civiles.add(new civil(motivo_reg, nombre, apellido, nacimiento, dep));
        lista_empleados.add(new empleado(puesto, experiencia, nombre, apellido, nacimiento, dep));

        jTextArea1.setText("Registrado: \n\n ");
        jTextArea1.setText(lista_civiles.getLast().toString());
        jTextArea1.setText(lista_empleados.getLast().toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_registrarMouseClicked

    private void boton_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_empleadoMouseClicked
        mostrarElementosEmpleado(rootPaneCheckingEnabled);
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_empleadoMouseClicked

    private void boton_civilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_civilMouseClicked
        mostrarElementosCivil(rootPaneCheckingEnabled);

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_civilMouseClicked

    private void boton_estadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_estadisticasMouseClicked
        jTextArea1.setText("Estadisticas"
                + "\nCiviviles: " + lista_civiles.size()
                + "\nEmpleados: " + lista_empleados.size()
        );

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_estadisticasMouseClicked

    /**
     * @param args the command line arguments
     */
    public void mostrarElementosEmpleado(boolean mostrar) {

        text_nombre.setVisible(mostrar);
        label_nombre.setVisible(mostrar);
        text_apellido.setVisible(mostrar);
        label_apellido.setVisible(mostrar);
        text_nacimiento.setVisible(mostrar);
        label_nacimiento.setVisible(mostrar);
        text_departamento.setVisible(mostrar);
        label_departamento.setVisible(mostrar);
        text_puesto.setVisible(mostrar);
        label_puesto.setVisible(mostrar);
        text_yearsXp.setVisible(mostrar);
        label_experiencia.setVisible(mostrar);
        boton_registrar.setVisible(mostrar);
        boton_morstarTodos.setVisible(mostrar);
        boton_buscarPorID.setVisible(mostrar);
        boton_estadisticas.setVisible(mostrar);
        text_BuscarID.setVisible(mostrar);
        label_buscarID.setVisible(mostrar);
        text_motivoRegistro.setVisible(false);
        label_motivoRegistro.setVisible(false);

    }

    public void mostrarElementosCivil(boolean mostrar) {

        text_nombre.setVisible(mostrar);
        label_nombre.setVisible(mostrar);
        text_apellido.setVisible(mostrar);
        label_apellido.setVisible(mostrar);
        text_nacimiento.setVisible(mostrar);
        label_nacimiento.setVisible(mostrar);
        text_departamento.setVisible(mostrar);
        label_departamento.setVisible(mostrar);
        text_motivoRegistro.setVisible(mostrar);
        label_motivoRegistro.setVisible(mostrar);
        boton_registrar.setVisible(mostrar);
        boton_morstarTodos.setVisible(mostrar);
        boton_buscarPorID.setVisible(mostrar);
        boton_estadisticas.setVisible(mostrar);
        text_BuscarID.setVisible(mostrar);
        label_buscarID.setVisible(mostrar);
        text_puesto.setVisible(false);
        label_puesto.setVisible(false);
        text_yearsXp.setVisible(false);
        label_experiencia.setVisible(false);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_buscarPorID;
    private javax.swing.JToggleButton boton_civil;
    private javax.swing.JToggleButton boton_empleado;
    private javax.swing.JToggleButton boton_estadisticas;
    private javax.swing.JToggleButton boton_morstarTodos;
    private javax.swing.JToggleButton boton_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_apellido;
    private javax.swing.JLabel label_buscarID;
    private javax.swing.JLabel label_departamento;
    private javax.swing.JLabel label_experiencia;
    private javax.swing.JLabel label_motivoRegistro;
    private javax.swing.JLabel label_nacimiento;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_puesto;
    private javax.swing.JTextField text_BuscarID;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_departamento;
    private javax.swing.JTextField text_motivoRegistro;
    private javax.swing.JTextField text_nacimiento;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_puesto;
    private javax.swing.JTextField text_yearsXp;
    // End of variables declaration//GEN-END:variables

    public static ArrayList<civil> lista_civiles;
    public static ArrayList<empleado> lista_empleados;
    public static ArrayList lista;

}
